name: example
description: "Fluent Emoji Example"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  fluent_emoji:
    path: ../packages/fluent_emoji
  fluent_emoji_widget:
    path: ../packages/fluent_emoji_widget

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
