name: fluent_emoji_update_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  console_bars: ^1.2.0
  archive: ^4.0.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
