name: fluent_emoji_publish
description: A sample command-line application with basic argument parsing.
version: 0.0.1
homepage: https://github.com/goweii/fluent_emoji

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.5.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
