name: fluent_emoji
description: "Fluent emoji package."
version: 0.0.1
homepage: https://github.com/goweii/fluent_emoji

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fluent_emoji_base: ^0.0.1
  fluent_emoji_activities: ^0.0.1
  fluent_emoji_animals_and_nature: ^0.0.1
  fluent_emoji_flags: ^0.0.1
  fluent_emoji_food_and_drink: ^0.0.1
  fluent_emoji_objects: ^0.0.1
  fluent_emoji_people_and_body: ^0.0.1
  fluent_emoji_smileys_and_emotion: ^0.0.1
  fluent_emoji_symbols: ^0.0.1
  fluent_emoji_travel_and_places: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
